### ISSUE TITLE
supported_languages() function Error

### ISSUE THREAD

**Issue by CheshireCC** [SYSTRAN/faster-whisper#498]
I used 
`from faster_whisper import supported_languages`
 to import `supported_languages()` function ，I got Error:
```
>>> from faster_whisper import supported_languages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\faster_whisper\__init__.py", line 2, in <module>
    from faster_whisper.transcribe import WhisperModel, Segment, Word, TranscriptionInfo
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\faster_whisper\transcribe.py", line 8, in <module>
    import ctranslate2
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\__init__.py", line 53, in <module>
    from ctranslate2 import converters, models, specs
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\converters\__init__.py", line 1, in <module>
    from ctranslate2.converters.converter import Converter
    from ctranslate2.specs.model_spec import ACCEPTED_MODEL_TYPES, ModelSpec
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\specs\__init__.py", line 1, in <module>
    from ctranslate2.specs.attention_spec import RotaryScalingType
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\specs\attention_spec.py", line 5, in <module>
    from ctranslate2.specs import common_spec, model_spec
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\specs\common_spec.py", line 3, in <module>
    from ctranslate2.specs import model_spec
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\ctranslate2\specs\model_spec.py", line 18, in <module>
    import torch
  File "d:\py_workspace\fatser_whsiper_GUI\python310\lib\site-packages\torch\__init__.py", line 249, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined
```

python: 3.10 with Conda
faster_whisper: 0.9.0
OS: Windows 11

**Comment by phineas-pta** [comment]
`supported_languages` is not a function but a property

```python
import faster_whisper
model = faster_whisper.WhisperModel("large-v2")
print(model.supported_languages)
```
