### ISSUE TITLE
Can't pass filename with space in it

### ISSUE THREAD

**Issue by escape0707** [SYSTRAN/faster-whisper#613]
When I'm using faster-whisper with whisper_ctranslate2, as I passed a file with a space in it's filename, say "2023 12 11.mkv", it complains a file not found error with part of the filename. Going through the mentioned source code, I see that str is used instead of a more safe and modern `pathlib.Path` object. Please consider migrate to `pathlib`.

https://github.com/SYSTRAN/faster-whisper/blob/65094b779e28e391bbba80a169e091144162db17/faster_whisper/audio.py#L46

```
Dec 11 00:26:34 gpu1 apptainer[223937]: File: '"~/audio/2023'
Dec 11 00:26:34 gpu1 apptainer[223937]: Traceback (most recent call last):
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "/usr/local/bin/whisper-ctranslate2", line 8, in <module>
Dec 11 00:26:34 gpu1 apptainer[223937]:     sys.exit(main())
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 547, in main
Dec 11 00:26:34 gpu1 apptainer[223937]:     result = transcribe.inference(
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/transcribe.py", line 130, in inference
Dec 11 00:26:34 gpu1 apptainer[223937]:     segments, info = self.model.transcribe(
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 277, in transcribe
Dec 11 00:26:34 gpu1 apptainer[223937]:     audio = decode_audio(audio, sampling_rate=sampling_rate)
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "/usr/local/lib/python3.10/dist-packages/faster_whisper/audio.py", line 46, in decode_audio
Dec 11 00:26:34 gpu1 apptainer[223937]:     with av.open(input_file, metadata_errors="ignore") as container:
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "av/container/core.pyx", line 401, in av.container.core.open
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "av/container/core.pyx", line 272, in av.container.core.Container.__cinit__
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "av/container/core.pyx", line 292, in av.container.core.Container.err_check
Dec 11 00:26:34 gpu1 apptainer[223937]:   File "av/error.pyx", line 336, in av.error.err_check
Dec 11 00:26:34 gpu1 apptainer[223937]: av.error.FileNotFoundError: [Errno 2] No such file or directory: '"~/audio/2023'

```

**Comment by patriotyk** [comment]
From your log output I see you pass cropped filename. Also you should not include "  in to the string.

**Comment by escape0707** [comment]
@patriotyk No, I did pass the full filename (which is a file that included some space characters in it), and I tried to include or not include `"` around the filename string and neither way worked. 

Maybe my first speculation is wrong, maybe the problem happened when faster-whisper interpret the argument I passed into it and failed to recognize that I have to use double quote to indicate that my filename include space in it.

Could you please give me an example of invoking faster-whisper against a file with space in its name?
