### ISSUE TITLE
lambda function whisper aws 

### ISSUE THREAD

**Issue by caioneves05** [SYSTRAN/faster-whisper#661]
I have this error here in AWS Lambda:

```
[ERROR] HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/var/task/var/task/../models/small'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/app.py", line 15, in <module>
    model = WhisperModel(model_folder, device="cpu", compute_type="int8")
  File "/var/lang/lib/python3.9/site-packages/faster_whisper/transcribe.py", line 124, in __init__
    model_path = download_model(
  File "/var/lang/lib/python3.9/site-packages/faster_whisper/utils.py", line 100, in download_model
    return huggingface_hub.snapshot_download(repo_id, **kwargs)
  File "/var/lang/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/var/lang/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
```

I'm trying to run the project in a lambda function through AWS, and importing the modules within my project, like this:

`
model_folder = os.path.join(os.path.dirname(__file__), '..', 'models', 'small')
`
`
model = WhisperModel(model_folder, device="cpu", compute_type="int8")
`
This is my folder structure:

![Captura de tela de 2024-01-29 10-08-07](https://github.com/SYSTRAN/faster-whisper/assets/80859717/d780e7d2-8d1e-46f1-80a0-43ecab102820)

I'm using `Dockerfile`, here it is:

```
FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt ${LAMBDA_TASK_ROOT}

COPY models ${LAMBDA_TASK_ROOT}

COPY audio.mp4 ${LAMBDA_TASK_ROOT}

RUN yum install -y pkgconfig

RUN pip install -r requirements.txt

COPY app.py ${LAMBDA_TASK_ROOT}

CMD ["app.handler"]

```

**Comment by trungkienbkhn** [comment]
@caioneves05 , hello. Can you show all the files in your `models/small/` directory. It should contain the files after converting using the below command:
`ct2-transformers-converter --model xxx --output_dir whisper-model --copy_files tokenizer.json preprocessor_config.json --quantization float16` 
Or could you replace the model_folder with model name (example 'small') then try again:
```python
model = WhisperModel("small", device="cpu", compute_type="int8")
```
