### ISSUE TITLE
silero_vad.onnx failed. File doesn't exist

### ISSUE THREAD

**Issue by ghj1976** [SYSTRAN/faster-whisper#753]
model.transcribe(fileName,vad_filter=True) 报错误文件不存在
```
[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\ADMINI~1\AppData\Local\Temp\_MEI92922\faster_whisper\assets\silero_vad.onnx failed:Load model C:\Users\ADMINI~1\AppData\Local\Temp\_MEI92922\faster_whisper\assets\silero_vad.onnx failed. File doesn't exist

Traceback (most recent call last):
  File "broadcast_record.py", line 100, in save_recording
  File "faster_whisper\transcribe.py", line 308, in transcribe
  File "faster_whisper\vad.py", line 86, in get_speech_timestamps
  File "faster_whisper\vad.py", line 241, in get_vad_model
  File "faster_whisper\vad.py", line 258, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 472, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\ADMINI~1\AppData\Local\Temp\_MEI92922\faster_whisper\assets\silero_vad.onnx failed:Load model C:\Users\ADMINI~1\AppData\Local\Temp\_MEI92922\faster_whisper\assets\silero_vad.onnx failed. File doesn't exist
```

**Comment by ghj1976** [comment]
我是pyinstaller打包方式运行的， 把faster-whisper打包了，但是没有打包silero_vad.onnx导致的。

解决方案：
pyinstaller --add-data="C:\Users\ghj1976\.conda\envs\zbj\Lib\site-packages\faster_whisper\assets\silero_vad.onnx;./faster_whisper/assets" 就解决了。
