### ISSUE TITLE
finetuning encounter multiple errors on the 2nd step (Fine-tuning XTTS Encoder)

### ISSUE THREAD

**Issue by tjw2469** [SYSTRAN/faster-whisper#838]
Error message:
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\utils\gpt_train.py", line 176, in train_gpt
    train_samples, eval_samples = load_tts_samples(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\TTS\tts\datasets\__init__.py", line 121, in load_tts_samples
    assert len(meta_data_train) > 0, f" [!] No training samples found in {root_path}/{meta_file_train}"
AssertionError:  [!] No training samples found in C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset/C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset\metadata_train.csv
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\utils\gpt_train.py", line 176, in train_gpt
    train_samples, eval_samples = load_tts_samples(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\TTS\tts\datasets\__init__.py", line 121, in load_tts_samples
    assert len(meta_data_train) > 0, f" [!] No training samples found in {root_path}/{meta_file_train}"
AssertionError:  [!] No training samples found in C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset/C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset\metadata_train.csv
", "", "", "", ""]
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1542, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1369, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\blocks.py", line 1343, in validate_outputs
    raise ValueError(
ValueError: An event handler (train_model) didn't receive enough output values (needed: 6, received: 5).
Wanted outputs:
    [label, textbox, textbox, textbox, textbox, textbox]
Received outputs:
    ["The training was interrupted due an error !! Please check the console to check the full error message!
 Error summary: Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\xtts_demo.py", line 358, in train_model
    speaker_xtts_path,config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(custom_model,version,language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=output_path, max_audio_length=max_audio_length)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\utils\gpt_train.py", line 176, in train_gpt
    train_samples, eval_samples = load_tts_samples(
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\TTS\tts\datasets\__init__.py", line 121, in load_tts_samples
    assert len(meta_data_train) > 0, f" [!] No training samples found in {root_path}/{meta_file_train}"
AssertionError:  [!] No training samples found in C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset/C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\finetune_models\dataset\metadata_train.csv
", "", "", "", ""]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\XXX\Desktop\xtts-webui\xtts-finetune-webui\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

I did my Data process (the 1st step) with a 163 seconds long .mp3 audio file. Successful.
For the 2nd step, I click "Load Params from output folder", and then click "Run the training". Error message
Is there any solution?

**Comment by phineas-pta** [comment]
wrong place to ask

**Comment by phineas-pta** [comment]
wrong place to ask
