### ISSUE TITLE
Language detection throws error when audio has no speech to transcribe in version 1.0.3

### ISSUE THREAD

**Issue by tamerxkilinc** [SYSTRAN/faster-whisper#893]
Hey, thanks for this awesome project! Been using it for a while now. I upgraded to version 1.0.3 and noticed, that there appears to be an unhandled exception when trying to transcribe an audio file without speech.

```
Traceback (most recent call last):
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/app/routers/transcribe.py", line 18, in transcribe
    transcriptions, language, duration = transcribe_with_model(whisper_model, job.url)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/app/transcription.py", line 10, in transcribe_with_model
    segments, info = model.transcribe(
                     ^^^^^^^^^^^^^^^^^
  File "/Users/tamerkilinc/git/whisper-transcription-service/myvenv/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 419, in transcribe
    language = max(
               ^^^^
ValueError: max() arg is an empty sequence
```

The issue occurs because `language_detection` is `{}` when the while condition is never met, so that the `max()` function call in the else case receives an empty sequence.

https://github.com/SYSTRAN/faster-whisper/blob/c22db5125d21d81744614f458b78604650038d3d/faster_whisper/transcribe.py#L392C17-L423C81

**Comment by tamerxkilinc** [comment]
To reproduce, you should activate the VAD filter so that the model does not hallucinate any "Thank you"s.

**Comment by trungkienbkhn** [comment]
@tamerxkilinc , yes it's an unhandled exception. It will be fixed in the next version. Now you can refer to this [fix](https://github.com/SYSTRAN/faster-whisper/issues/889#issuecomment-2204967791)
