### ISSUE TITLE
ImportError: cannot import name 'WhisperModel' from partially initialized module 'faster_whisper'

### ISSUE THREAD

**Issue by nullonesix** [SYSTRAN/faster-whisper#905]
faster_whisper.py:

```py

from faster_whisper import WhisperModel

model_size = "large-v3"

# Run on GPU with FP16
model = WhisperModel(model_size, device="cuda", compute_type="float16")

# or run on GPU with INT8
# model = WhisperModel(model_size, device="cuda", compute_type="int8_float16")
# or run on CPU with INT8
# model = WhisperModel(model_size, device="cpu", compute_type="int8")

segments, info = model.transcribe("audio.mp3", beam_size=5)

print("Detected language '%s' with probability %f" % (info.language, info.language_probability))

for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
    
```

me attempting to run it:

```
python3 faster_whisper.py
Traceback (most recent call last):
  File "/home/swarms/faster_whisper.py", line 1, in <module>
    from faster_whisper import WhisperModel
  File "/home/swarms/faster_whisper.py", line 1, in <module>
    from faster_whisper import WhisperModel
ImportError: cannot import name 'WhisperModel' from partially initialized module 'faster_whisper' (most likely due to a circular import) 
```

**Comment by ooobo** [comment]
Rename your script from faster_whisper.py to something else
